routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', function () {
    return view('home');
})->middleware('auth');


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/profile', 'ProfileController@index')->name('profile');

Route::resource('/compagny', 'CompagnyController')->middleware('auth');
Route::post('/compagny/store', 'CompagnyController@store')->name('posts');
Route::put('/compagny/update','CompagnyController@update')->name('update');
Route::post('/compagny/changeStatus', 'CompagnyController@changeStatus')->name('changeStatus');


Route::resource('/userController','UserContoller')->middleware('auth');
//Route::post('/userController/store','UserContoller@store')->name('posts');
//Route::put('/userController/update','UserContoller@update')->name('update');
Route::post('/userController/changeStatus', 'UserContoller@changeStatus')->name('changeStatus');
// Route::post('/userController/changeStatus', array('as'=>'changeStatus','uses'=>'UserContoller@changeStatus'));

Route::resource('/timesheet','TimeSheetController')->middleware('auth');
Route::post('/timesheet/store','TimeSheetController@store')->name('timesheet.store');
Route::put('/timesheet','TimeSheetController@sheetupdate')->name('sheetupdate');
Route::post('/timesheets/selectTache','TimeSheetController@selectTache')->name('selectTache');
Route::get('/timesheets/search','TimeSheetController@search')->name('search');
//Route::get('/timesheet/{getuuid}', 'TimeSheetController@getuuid')->name('getuuid');
//Route::resource('/timesheetlist/getuuid','ListTimeSheetController');
Route::post('/timesheet','TimeSheetController@getuuid')->name('getuuid');
Route::post('/timesheet/exportAdmin','TimeSheetController@exportAdmin')->name('exportAdmin');
Route::post('/timesheet/active','TimeSheetController@active')->name('active');
Route::post('/timesheet/addSheet','TimeSheetController@addSheet')->name('addSheet');
Route::post('/timesheet/deleteSheet','TimeSheetController@deleteSheet')->name('deleteSheet');

Route::resource('/departement', 'DepartementController')->middleware('auth');

Route::resource('/tache', 'TacheController')->middleware('auth');

Route::get('/timesheet-csv', function() {

    $headers = array(
          'Content-Type' => 'application/vnd.ms-excel; charset=utf-8',
          'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
          'Content-Disposition' => 'attachment; filename=abc.csv',
          'Expires' => '0',
          'Pragma' => 'public',
      );

  $filename = "timesheets.csv";
  $handle = fopen($filename, 'w');
  fputcsv($handle, [
      'id',
      'user_id',
      'employe',
      'date',
      'dossier',
      'client',
      'titreTache',
      'debut',
      'fin',
      'temps',
      'departement',
      'codeTache',
      'comment',
      'uuidTimeSheet',
      '_token',
      'nbligne',
      'created_at',
      'updated_at'
  ]);

  DB::table("timesheets")->orderBy('employe')->chunk(100, function ($data) use ($handle) {
      foreach ($data as $row) {
          // Add a new row with data
          fputcsv($handle, [
            $row->id,
            $row->user_id,
            $row->employe,
            $row->date,
            $row->dossier,
            $row->client,
            $row->titreTache,
            $row->debut,
            $row->fin,
            $row->temps,
            $row->departement,
            $row->codeTache,
            $row->comment,
            $row->uuidTimeSheet,
            $row->_token,
            $row->nbligne,
            $row->created_at,
            $row->updated_at
          ]);
      }
  });

  fclose($handle);

  return Response::download($filename, "timesheets.csv", $headers);

});

resources/views/departementAjax.blade.php
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

<!-- Bootstrap JavaScript -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/js/bootstrap.min.js"></script>

<!-- toastr notifications -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<!-- icheck checkboxes -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.js"></script>

<!-- Delay table load until everything else is loaded -->
<script>
    $(window).load(function(){
        $('#postTable').removeAttr('style');
    })
</script>


<!-- AJAX CRUD operations -->
<script type="text/javascript">
      $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
      });
    // add a new post
    $(document).on('click', '.add-modal', function() {
        $('.modal-title').text('Add');
        $('#addModal').modal('show');

    });


    $('.modal-footer').on('click', '.add', function() {


        $.ajax({
            type: 'POST',
            url: "{{ route('departement.store')}}",
            data: {
                '_token': $('input[name=_token]').val(),
                'name': $('#name_add').val(),
                'code': $('#code_add').val(),
            },
            success: function(data) {

                $('.errorCode').addClass('hidden');
                $('.errorName').addClass('hidden');

                if ((data.errors)) {
                    setTimeout(function () {
                        $('#addModal').modal('show');
                        toastr.error('Validation error!', 'Error Alert', {timeOut: 5000});
                    }, 500);

                    if (data.errors.code) {
                        $('.errorCode').removeClass('hidden');
                        $('.errorCode').text(data.errors.code);
                    }
                    if (data.errors.name) {
                        $('.errorName').removeClass('hidden');
                        $('.errorName').text(data.errors.name);
                    }
                } else {

                    toastr.success('Successfully added Post!', 'Success Alert', {timeOut: 5000});
                    $('#postTable').append("<tr class='item" + data.id + "'><td>" + data.id + "</td><td>" + data.code+ "</td><td>" + data.name + "</td><td><button class='edit-modal btn btn-info' data-id='" + data.id + "' data-code='" + data.code + "' data-name='" + data.name + "'><span><i class='fa fa-edit'></i></span> Edit</button> <button class='delete-modal btn btn-danger' data-id='" + data.id + "' data-code='" + data.code + "' data-name='" + data.name +  "'><span><i class='fa fa-trash-o'></i></span> Delete</button></td></tr>");

                }
            },
        });
    });

    // Show a post
    // $(document).on('click', '.show-modal', function() {
    //     $('.modal-title').text('Show');
    //     $('#id_show').val($(this).data('id'));
    //     $('#name_show').val($(this).data('name'));
    //     $('#email_show').val($(this).data('email'));
    //     $('#showModal').modal('show');
    // });
    //

    // Edit a post
    $(document).on('click', '.edit-modal', function() {
        $('.modal-title').text('Edit');
        $('#id_edit').val($(this).data('id'));
        $('#code_edit').val($(this).data('code'));
        $('#name_edit').val($(this).data('name'));
        $('#editModal').modal('show');
    });
    $('.modal-footer').on('click', '.edit', function() {

        $.ajax({
            type: 'PUT',
            url: 'departement/'+id,
            data: {
                '_token': $('input[name=_token]').val(),
                'id': $("#id_edit").val(),
                'code': $('#code_edit').val(),
                'name': $('#name_edit').val(),
            },
            success: function(data) {
                $('.errorCode').addClass('hidden');
                $('.errorName').addClass('hidden');

                if ((data.errors)) {
                    setTimeout(function () {
                        $('#editModal').modal('show');
                        toastr.error('Validation error!', 'Error Alert', {timeOut: 5000});
                    }, 500);

                    if (data.errors.code) {
                        $('.errorCode').removeClass('hidden');
                        $('.errorCode').text(data.errors.code);
                    }
                    if (data.errors.name) {
                        $('.errorName').removeClass('hidden');
                        $('.errorName').text(data.errors.name);
                    }
                } else {
                    toastr.success('Successfully updated Post!', 'Success Alert', {timeOut: 5000});
                    $('.item' + data.id).replaceWith("<tr class='item" + data.id + "'><td>" + data.id + "</td><td>" + data.code+ "</td><td>" + data.name + "</td><td><button class='edit-modal btn btn-info' data-id='" + data.id + "' data-code='" + data.code + "' data-name='" + data.name + "'><span><i class='fa fa-edit'></i></span> Edit</button> <button class='delete-modal btn btn-danger' data-id='" + data.id + "' data-code='" + data.code + "' data-name='" + data.name +  "'><span><i class='fa fa-trash-o'></i></span> Delete</button></td></tr>");
                }
            }
        });
    });

    // delete a post
    $(document).on('click', '.delete-modal', function() {
        $('.modal-title').text('Delete');
        $('#id_delete').val($(this).data('id'));
        $('#name_delete').val($(this).data('name'));
        $('#deleteModal').modal('show');
        id = $('#id_delete').val();
    });
    $('.modal-footer').on('click', '.delete', function() {
        $.ajax({
            type: 'DELETE',
            url: 'departement/'+id,
            data: {
                '_token': $('input[name=_token]').val(),
            },
            success: function(data) {
                toastr.success('Successfully deleted Post!', 'Success Alert', {timeOut: 5000});
                $('.item' + data['id']).remove();
            }
        });
    });
</script>

</body>
</html>

resources/views/home.blade.php
@extends('layouts.dashboard')

@section('page_title')
	Welcome
@stop


@section('dashboard-content')

<div class="container-fluid home-page">
	<div class="row">
		<div class="col-md-6 calendar-col">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Welcome {{Auth::user()->name}}</h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-4 calendar-wrapper">
							<div class="today">
								<h2 class="date"></h2>  <span class="month"></span>
							</div>
						</div>
						<div class="col-md-8 calendar-widget">
							<div id="calendar2"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 graph-col">
			<!-- <div class="panel panel-default line-chart">
				<div class="panel-body">
					<div class="line-chart-container">
						<canvas id="home-line-chart"></canvas>
					</div>
				</div>
			</div> -->
		</div>
	</div>
	<div>

	</div>

</div>

@stop

@section('js')

	@parent

	<script>

		$(function(){


			// Activate Calendar

			$('#calendar2').fullCalendar({
			});




			// Line chart
			var lineChartData1 = {
	            labels : ["","","","","","","","","","","",""],
	            datasets : [
	                {
	                    label: "My First dataset",
	                    fillColor : "rgba(6, 197, 172, 0.5)",
	                    strokeColor : "rgba(6, 197, 172, 1)",
	                    pointColor : "rgba(6, 197, 172, 1)",
	                    pointStrokeColor : "#fff",
	                    pointHighlightFill : "#fff",
	                    pointHighlightStroke : "rgba(6, 197, 172, 1)",
	                    data : [65,59,80,81,56,55,40,74,36,65,33,55]
	                },
	                {
	                    label: "My Second dataset",
	                    fillColor : "rgba(244, 204, 11, 0.5)",
	                    strokeColor : "rgba(244, 204, 11, 1)",
	                    pointColor : "rgba(244, 204, 11, 1)",
	                    pointStrokeColor : "#fff",
	                    pointHighlightFill : "#fff",
	                    pointHighlightStroke : "rgba(244, 204, 11, 1)",
	                    data : [28,48,40,29,86,27,60,45,27,59,68,38]
	                }
	            ]

	        };


	        var homeLineChart = document.getElementById("home-line-chart").getContext("2d");

	        var chartCurves = new Chart(homeLineChart).Line(lineChartData1, {
	            responsive: true,
	            scaleShowLabels:false,
	            scaleShowGridLines : false,
			    scaleShowHorizontalLines: false,
			    scaleShowVerticalLines: false,
	            pointDot: false
	        });

    		// Set the date
    		$('.today .date').text((new Date).getDate());

    		var months = [
    			"January",
	    		"February",
	    		"March",
	    		"April",
	    		"May",
	    		"June",
	    		"July",
	    		"August",
	    		"September",
	    		"October",
	    		"November",
	    		"December"
    		];

    		$('.today .month').text(months[(new Date).getMonth()]);

		});

	</script>



@endsection

resources/views/modalCompNew.blade.php
@extends('layouts.dashboard')



@section('page_title')
	Company Management
@stop
@section('page_subtitle')
Bootstrap UI Components
@stop
@section('page_heading')
	Company Management
@stop
@section('dashboard-content')

<div class="row">
	<div class="col-sm-12">
		 @section ('htable_panel_title','List of Companies')
	@section ('htable_panel_body')
		@include('widgets.tableComp', array('class'=>'table-hover'))
		@endsection
	 @include('widgets.panel', array('class'=>'success', 'controls'=>true, 'header'=>true, 'as'=>'htable'))
	</div>
</div>




		 <button type="button" class="btn btn-primary btn-rounded" style=" position: fixed; bottom: 20px; right: 20px; margin-bottom:40px;" data-toggle="modal" data-target="#myModal2">
			 <i class="fa fa-plus" style="font-size:20px;"></i>
		 </button>
		


 <!-- @include('widgets.panel', array('class'=>'primary', 'header'=>true, 'as'=>'modal1')) -->



@stop

resources/views/modalCompUpdate.blade.php
<div class="modal fade" id="modalCompUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">

      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel"></h4>
    </div>

    <div class="modal-body">
      <div class="conter-wrapper">
      <div class="row">
      <div class="col-md-12">
      <div class="panel panel-primary">
      <div class="panel-body">
      <form id="formUpdate" class="form-horizontal" method="POST" action="{{ route('register') }}" novalidate>
        @csrf
        <div class="form-group">
        <label for="inputtext" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
        <input type="text" class="form-control underline" name="name" id="name" placeholder="Compagny Name">
        </div>
        </div>

      <hr/>

        <div class="form-group">
        <label for="inputtext" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
        <input type="text" class="form-control underline" name="email" id="Email" placeholder="Email">
        </div>
        </div>

      <hr/>

        <div class="form-group">
        <label for="inputtext" class="col-sm-2 control-label">Address</label>
        <div class="col-sm-10">
        <input type="text" class="form-control underline" name="Address" id="Address" placeholder="Address">
        </div>
        </div>

      <hr/>

      </div>
      </div>
      </div>
      </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default btn-rounded" data-dismiss="modal">Cancel</button>
      <button type="submit" class="btn btn-primary btn-rounded" value="Publier">Update</button>
    </div>
    </form>
  </div>
</div>
</div>

resources/views/userControllerAjax.blade.php
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

<!-- Bootstrap JavaScript -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.1/js/bootstrap.min.js"></script>

<!-- toastr notifications -->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<!-- icheck checkboxes -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.js"></script>

<!-- Delay table load until everything else is loaded -->
<script>
    $(window).load(function(){
        $('#postTable').removeAttr('style');
    })
</script>


<!-- AJAX CRUD operations -->
<script type="text/javascript">
      $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
      });
    // add a new post
    $(document).on('click', '.add-modal', function() {
        $('.modal-title').text('Add');
        $('#addModal').modal('show');

    });

    $(document).ready(function(){
              // $('.published').iCheck({
              //     checkboxClass: 'icheckbox_square-yellow',
              //     radioClass: 'iradio_square-yellow',
              //     increaseArea: '20%'
              // });
              $('.published').on('click', function(event){
                  id = $(this).data('id');
                  if($(this).is(":checked")) {
                        var active = 1;
                    } else {
                        var active = 0;
                    }
                  $.ajax({
                      type: 'POST',
                      url: "userController/changeStatus",
                      data: {
                          '_token': $('input[name=_token]').val(),
                          'id': id,
                          'active': active
                      },
                      success: function(data) {
                          // empty
                      },
                  });
              });
              $('.published').on('ifToggled', function(event) {
                  $(this).closest('tr').toggleClass('warning');
              });
          });



    $('.modal-footer').on('click', '.add', function() {

      if($('#switch_add').is(":checked")) {

            var active = 1;
            var checked = 'checked';
        } else {
            var active = 0;
            var checked = '';
        }

        $.ajax({
            type: 'POST',
            url: "{{ route('userController.store')}}",
            data: {
                '_token': $('input[name=_token]').val(),
                'active': active,
                // 'compagny': $('#compagny_add').val(),
                'name': $('#name_add').val(),
                'email': $('#email_add').val(),
                'password': $('#password_add').val(),
                'confirmpassword': $('#confirmpassword_add').val(),
                'role': $('#role_add').val(),

            },
            success: function(data) {

                $('.errorTitle').addClass('hidden');
                $('.errorContent').addClass('hidden');

                if ((data.errors)) {
                    setTimeout(function () {
                        $('#addModal').modal('show');
                        toastr.error('Validation error!', 'Error Alert', {timeOut: 5000});
                    }, 500);

                    if (data.errors.name) {
                        $('.errorName').removeClass('hidden');
                        $('.errorName').text(data.errors.name);
                    }
                    if (data.errors.email) {
                        $('.errorEmail').removeClass('hidden');
                        $('.errorEmail').text(data.errors.email);
                    }
                    if (data.errors.password) {
                        $('.errorPassword').removeClass('hidden');
                        $('.errorPassword').text(data.errors.password);
                    }
                    if (data.errors.confirmpassword) {
                        $('.errorConfirmpassword').removeClass('hidden');
                        $('.errorConfirmpassword').text(data.errors.confirmpassword);
                    }
                } else {

                    toastr.success('Successfully added!', 'Success Alert', {timeOut: 5000});
                    $('#postTable').append("<tr class='item" + data.id + "'><td>" + data.id + "</td><td>" + data.name + "</td><td>" + data.email + "</td><td>" + data.role + "</td><td class='text-center'><input type='checkbox' id='active_add' class='published' "+checked+"></td><td>Right now</td><td><button class='edit-modal btn btn-info' data-id='" + data.id + "' data-name='" + data.name + "' data-email='" + data.email + "'><span><i class='fa fa-edit'></i></span> Edit</button> <button class='delete-modal btn btn-danger' data-id='" + data.id + "' data-name='" + data.name + "' data-email='" + data.email + "'><span><i class='fa fa-trash-o'></i></span> Delete</button></td></tr>");

                }
            },
        });
    });
    // Show a post
    $(document).on('click', '.show-modal', function() {
        $('.modal-title').text('Show');
        $('#id_show').val($(this).data('id'));
        $('#name_show').val($(this).data('name'));
        $('#email_show').val($(this).data('email'));
        $('#showModal').modal('show');
    });

var i =0;
    // Edit a post
    $(document).on('click', '.edit-modal', function() {

        $('.modal-title').text('Edit');
        $('#id_edit').val($(this).data('id'));
        $('#name_edit').val($(this).data('name'));
        $('#email_edit').val($(this).data('email'));
        $('#active_edit').val($(this).data('active'));
        $('#role_edit').val($(this).data('role'));
        id = $('#id_edit').val();
        if($('#userActive'+id+'').is(":checked")) {
            var checked = true;
          } else {
             var checked = false;
          }
        $('#switch_edit').prop("checked", checked);
        $('#editModal').modal('show');
        //$('#switch_edit').remplaceWith('<input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="switch_edit"> checked="1"');
    });

    $('.modal-footer').on('click', '.edit', function() {

            if($('#switch_edit').is(":checked")) {
                var active = 1;
                var checked = 'checked';
            } else {
                var active = 0;
                var checked = '';
            }

        $.ajax({
            type: 'PUT',
            url: 'userController/'+id,
            data: {
                '_token': $('input[name=_token]').val(),
                'id': $("#id_edit").val(),
                'active': active,
                // 'compagny': $('#compagny_edit').val(),
                'name': $('#name_edit').val(),
                'email': $('#email_edit').val(),
                'password': $('#password_edit').val(),
                'confirmpassword': $('#confirmpassword_edit').val(),
                'role': $('#role_edit').val(),
            },
            success: function(data) {
                $('.errorName').addClass('hidden');
                $('.errorEmail').addClass('hidden');

                if ((data.errors)) {
                    setTimeout(function () {
                        $('#editModal').modal('show');
                        toastr.error('Validation error!', 'Error Alert', {timeOut: 5000});
                    }, 500);

                    if (data.errors.name) {
                        $('.errorName').removeClass('hidden');
                        $('.errorName').text(data.errors.name);
                    }
                    if (data.errors.email) {
                        $('.errorEmail').removeClass('hidden');
                        $('.errorEmail').text(data.errors.email);
                    }
                    if (data.errors.password) {
                        $('.errorPassword').removeClass('hidden');
                        $('.errorPassword').text(data.errors.password);
                    }
                    if (data.errors.confirmpassword) {
                        $('.errorConfirmpassword').removeClass('hidden');
                        $('.errorConfirmpassword').text(data.errors.confirmpassword);
                    }
                } else {
                    toastr.success('Successfully updated!', 'Success Alert', {timeOut: 5000});
                    $('.item' + data.id).replaceWith("<tr class='item" + data.id + "'><tr class='item" + data.id + "'><td>" + data.id + "</td><td>" + data.name + "</td><td>" + data.email + "</td><td>" + data.role + "</td><td class='text-center'><input type='checkbox' id='active_add' class='published' "+data.active+"></td><td>Right now</td><td><button class='edit-modal btn btn-info' data-id='" + data.id + "' data-name='" + data.name + "' data-email='" + data.email + "'><span><i class='fa fa-edit'></i></span> Edit</button> <button class='delete-modal btn btn-danger' data-id='" + data.id + "' data-name='" + data.name + "' data-email='" + data.email + "'><span><i class='fa fa-trash-o'></i></span> Delete</button></td></tr>");
                }
            }
        });
    });

    // delete a post
    $(document).on('click', '.delete-modal', function() {
        $('.modal-title').text('Delete');
        $('#id_delete').val($(this).data('id'));
        $('#name_delete').val($(this).data('name'));
        $('#deleteModal').modal('show');
        id = $('#id_delete').val();
    });
    $('.modal-footer').on('click', '.delete', function() {
        $.ajax({
            type: 'DELETE',
            url: 'userController/'+id,
            data: {
                '_token': $('input[name=_token]').val(),
            },
            success: function(data) {
                toastr.success('Successfully deleted!', 'Success Alert', {timeOut: 5000});
                $('.item' + data['id']).remove();
            }
        });
    });
</script>

</body>
</html>

resources/views/users.blade.php
@extends('layouts.dashboard')

@section('page_title')
	Tables
@stop
@section('page_subtitle')
Bootstrap UI Components
@stop
@section('page_heading')
	Tables
@stop
@section('dashboard-content')


<div class="row">
	<div class="col-md-6">
		@section ('htable_panel_title','Hover Table')
		@section ('htable_panel_body')
		@include('widgets.table', array('class'=>'table-hover'))
		@endsection
		@include('widgets.panel', array('class'=>'success', 'controls'=>true, 'header'=>true, 'as'=>'htable'))
	</div>
</div>


<div class="row">
	<div class="col-sm-12">
		@section ('cotable_panel_title','Coloured Table')
		@section ('cotable_panel_body')
			<table class="table table-bordered white">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
						<th>Address</th>
					</tr>
				</thead>
				<tbody>
					<tr class="success">
						<td>John</td>
						<td>john@gmail.com</td>
						<td>London, UK</td>
					</tr>
					<tr class="info">
						<td>Andy</td>
						<td>andy@gmail.com</td>
						<td>Merseyside, UK</td>
					</tr>
					<tr class="warning">
						<td>Frank</td>
						<td>frank@gmail.com</td>
						<td>Southampton, UK</td>
					</tr>
					<tr class="danger">
						<td>Rickie</td>
						<td>rickie@gmail.com</td>
						<td>Burnley, UK</td>
					</tr>
				</tbody>
			</table>
		@endsection
		@include('widgets.panel', array('controls'=>true, 'header'=>true, 'as'=>'cotable'))
	</div>
</div>
@stop